[package]
name = "tiny_http_client"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Tiny synchronous HTTP/HTTPS GET client"
repository = "https://github.com/ygguser/tiny_http_client"
build = "build.rs"
include = [
    "src/**/*",
    "certs/*.der",
    "build.rs",
    "macos/network_tls.c",
    "Cargo.toml",
    "LICENSE",
    "README.md",
]

[features]
default = []
own-cert-list = []

[target.'cfg(target_os = "linux")'.dependencies]
rustls = { version = "0.23", default-features = false, features = ["std", "ring"] }
webpki-roots = { version = "0.26", default-features = false }

[target.'cfg(windows)'.dependencies]
native-tls = "0.2"

[profile.release]
strip = true
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
